# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_sys_ipc
    test_fault_wrappers_sys_mman
    test_fault_wrappers_sys_msg
    test_fault_wrappers_sys_sem
    test_fault_wrappers_sys_shm
    test_fault_wrappers_sys_stat
    test_fault_wrappers_unistd
)
